/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/extension/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_identity_extension_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/extension-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_extension_token_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_identity_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/extension-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_identity_extension_token_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extension/companies/{companyId}/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ingestion_extension_company_skus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ingestion_company_connections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/ingestion/ozon/sales-facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ingestion_ozon_sales_facts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/connections/{marketplaceAccountId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_ingestion_connection_credentials_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extension/companies/{companyId}/skus/{marketplaceSku}/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ingestion_extension_sku_sales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/unit-economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ingestion_unit_economics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_admin_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seller/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_seller_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeCompanyResponse: {
            id: string;
            name: string;
        };
        ExtensionMeResponse: {
            email: string;
            company: components["schemas"]["MeCompanyResponse"];
        };
        ValidationErrorResponse: {
            status: number;
            code: string;
            message: string;
        };
        IssueExtensionTokenResponse: {
            id: string;
            token: string;
            tokenPrefix: string;
            expiresAt: string;
        };
        LoginResponse: {
            email: string;
        };
        MeResponse: {
            email: string;
            companies: components["schemas"]["MeCompanyResponse"][];
        };
        CompanySkuListResponse: {
            items: string[];
            nextCursor?: string | null;
        };
        ConnectionResponse: {
            id: string;
            marketplace: string;
            externalShopId: string;
            state: string;
            createdAt: string;
            lastLoadedAt: {
                [key: string]: string;
            };
            /**
             * Версия для оптимистической блокировки (ADR-008): клиент
             *     присылает её обратно при замене ключей.
             */
            version: number;
        };
        ConnectionsResponse: {
            connections: components["schemas"]["ConnectionResponse"][];
        };
        SalesFactListItemResponse: {
            marketplaceAccountId: string;
            sourceRowId: string;
            businessDate: string;
            status: string;
            marketplaceSku: string;
            quantity: number;
            amountMinor: number;
            commissionAmountMinor: number;
            currency: string;
        };
        SalesFactListResponse: {
            items: components["schemas"]["SalesFactListItemResponse"][];
            nextCursor?: string | null;
        };
        ReplacedCredentialsResponse: {
            id: string;
            state: string;
        };
        SkuSalesTotalResponse: {
            currency: string;
            orderedQuantity: number;
            orderedAmountMinor: number;
            deliveredQuantity: number;
            deliveredAmountMinor: number;
            cancelledQuantity: number;
            cancelledAmountMinor: number;
        };
        SkuSalesSummaryResponse: {
            marketplaceSku: string;
            days: number;
            totals: components["schemas"]["SkuSalesTotalResponse"][];
        };
        UnitEconomicsExpenseResponse: {
            feeTypeId: number;
            name: string;
            amountMinor: number;
        };
        UnitEconomicsSkuResponse: {
            marketplaceSku: string;
            deliveredQuantity: number;
            orderedQuantity: number;
            revenueMinor: number;
            commissionMinor: number;
            expenses: components["schemas"]["UnitEconomicsExpenseResponse"][];
            expensesTotalMinor: number;
            marginMinor: number;
        };
        UnitEconomicsResponse: {
            from: string;
            to: string;
            currency: string;
            skus: components["schemas"]["UnitEconomicsSkuResponse"][];
            cabinetExpenses: components["schemas"]["UnitEconomicsExpenseResponse"][];
            cabinetExpensesTotalMinor: number;
        };
        AppInfoResponse: {
            app: string;
            version: string;
            respondedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_identity_extension_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь и компания, к которым привязан предъявленный токен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionMeResponse"];
                };
            };
            /** @description Токен отсутствует, истёк, отозван или участник исключён из компании */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    post_identity_extension_token_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токен выпущен. Поле token отдаётся единственный раз и больше не восстанавливается. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueExtensionTokenResponse"];
                };
            };
        };
    };
    post_identity_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Вход выполнен, сессия установлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Неверный email или пароль — сообщение одинаково для обоих случаев (ADR-007) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_identity_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий пользователь и компании, доступные ему по членству */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    delete_identity_extension_token_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токен отозван. Повторный отзыв идемпотентен. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Токена с таким id в этой компании нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_ingestion_extension_company_skus: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Артикул из nextCursor предыдущей страницы */
                cursor?: string;
            };
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Артикулы компании, keyset-пагинация по самому артикулу */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySkuListResponse"];
                };
            };
            /** @description Токен отсутствует или недействителен */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Некорректный limit */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_ingestion_company_connections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Подключения компании с состоянием и моментом последней загрузки по каждой выгрузке */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
            /** @description Пользователь не состоит в этой компании */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_ingestion_ozon_sales_facts_list: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Курсор из nextCursor предыдущей страницы */
                cursor?: string;
            };
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список продаж компании, keyset-пагинация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesFactListResponse"];
                };
            };
            /** @description Некорректный limit или cursor */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    put_ingestion_connection_credentials_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
                marketplaceAccountId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    clientId: string;
                    apiKey: string;
                    /** @description Версия подключения из ответа списка (ADR-008) */
                    version: number;
                };
            };
        };
        responses: {
            /** @description Ключ принят площадкой и сохранён; сломанное подключение возвращено в работу */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplacedCredentialsResponse"];
                };
            };
            /** @description Пользователь не состоит в этой компании */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description У этой компании нет такого подключения */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Подключение изменил кто-то ещё — перечитать и повторить (ADR-008) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Площадка не приняла ключ либо тело запроса неполное */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_ingestion_extension_sku_sales: {
        parameters: {
            query?: {
                /** @description Окно в днях по бизнес-дате площадки */
                days?: number;
            };
            header?: never;
            path: {
                companyId: string;
                marketplaceSku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказанное и отменённое по артикулу за окно дней, по каждой валюте отдельно */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuSalesSummaryResponse"];
                };
            };
            /** @description Токен отсутствует или недействителен */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Некорректный days */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_ingestion_unit_economics: {
        parameters: {
            query?: {
                /** @description Окно в днях по бизнес-дате площадки */
                days?: number;
            };
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Экономика по артикулам и расходы кабинета за период */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitEconomicsResponse"];
                };
            };
            /** @description Пользователь не состоит в этой компании */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Некорректный days */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_admin_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о приложении */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfoResponse"];
                };
            };
        };
    };
    get_seller_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о приложении */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfoResponse"];
                };
            };
        };
    };
}
