<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808180545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Raw-слой: marketplace_raw_document (ADR-006); messenger_messages — таблица Doctrine-транспорта.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE marketplace_raw_document (id UUID NOT NULL, company_id UUID NOT NULL, marketplace_account_id UUID NOT NULL, report_type VARCHAR(64) NOT NULL, period DATE NOT NULL, body_hash VARCHAR(64) NOT NULL, body JSONB NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_marketplace_raw_document_company_id ON marketplace_raw_document (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_marketplace_raw_document_natural_key ON marketplace_raw_document (company_id, marketplace_account_id, report_type, period, body_hash)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE marketplace_raw_document');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
