<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808174351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Identity minimum: company, marketplace_account (ADR-002, ADR-007); messenger_messages — таблица Doctrine-транспорта, без неё воркеры уходят в цикл перезапуска.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id UUID NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE marketplace_account (id UUID NOT NULL, company_id UUID NOT NULL, marketplace VARCHAR(32) NOT NULL, external_shop_id VARCHAR(255) NOT NULL, credentials_ciphertext TEXT NOT NULL, credentials_key_version SMALLINT NOT NULL, state VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_marketplace_account_company_id ON marketplace_account (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_marketplace_account_company_marketplace_external_shop ON marketplace_account (company_id, marketplace, external_shop_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE marketplace_account');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
